// JBV: BEGIN privacy page
export const metadata = { title: "Privacy | JBV Capital" };

export default function PrivacyPage() {
  return (
    <main className="max-w-3xl mx-auto px-6 md:px-8 py-12 prose prose-invert prose-a:text-blue-300">
      <h1 className="text-2xl font-semibold mb-4">Privacy</h1>
      <div className="space-y-4 text-sm leading-6">
        <p>Views expressed in “posts” (including podcasts, videos, and social media) are those of the individual JBV Capital personnel quoted therein and are not the views of JBV Capital Management, L.L.C. (“JBV Capital”) or its respective affiliates. JBV Capital Management is an investment adviser registered with the Securities and Exchange Commission. Registration as an investment adviser does not imply any special skill or training. The posts are not directed to any investors or potential investors, and do not constitute an offer to sell — or a solicitation of an offer to buy — any securities, and may not be used or relied upon in evaluating the merits of any investment.</p>
        <p>The contents in here — and available on any associated distribution platforms and any public JBV Capital online social media accounts, platforms, and sites (collectively, “content distribution outlets”) — should not be construed as or relied upon in any manner as investment, legal, tax, or other advice. You should consult your own advisers as to legal, business, tax, and other related matters concerning any investment. Any projections, estimates, forecasts, targets, prospects and/or opinions expressed in these materials are subject to change without notice and may differ or be contrary to opinions expressed by others. Any charts provided here or on JBV Capital content distribution outlets are for informational purposes only, and should not be relied upon when making any investment decision. Certain information contained in here has been obtained from third-party sources, including from portfolio companies of funds managed by JBV Capital. While taken from sources believed to be reliable, JBV Capital has not independently verified such information and makes no representations about the enduring accuracy of the information or its appropriateness for a given situation. In addition, posts may include third-party advertisements; JBV Capital has not reviewed such advertisements and does not endorse any advertising content contained therein. All content speaks only as of the date indicated.</p>
        <p>Under no circumstances should any posts or other information provided on this website — or on associated content distribution outlets — be construed as an offer soliciting the purchase or sale of any security or interest in any pooled investment vehicle sponsored, discussed, or mentioned by JBV Capital personnel. Nor should it be construed as an offer to provide investment advisory services; an offer to invest in a JBV Capital-managed pooled investment vehicle will be made separately and only by means of the confidential offering documents of the specific pooled investment vehicles — which should be read in their entirety, and only to those who, among other requirements, meet certain qualifications under federal securities laws. Such investors, defined as accredited investors and qualified purchasers, are generally deemed capable of evaluating the merits and risks of prospective investments and financial matters.</p>
        <p>There can be no assurances that JBV Capital’s investment objectives will be achieved or investment strategies will be successful. Any investment in a vehicle managed by JBV Capital involves a high degree of risk including the risk that the entire amount invested is lost. Any investments or portfolio companies mentioned, referred to, or described are not representative of all investments in vehicles managed by JBV Capital and there can be no assurance that the investments will be profitable or that other investments made in the future will have similar characteristics or results. A list of investments made by funds managed by JBV Capital is available here: <a href="https://jbvcapital.com/investments/" target="_blank" rel="noopener noreferrer">https://jbvcapital.com/investments/</a>. Past results of JBV Capital’s investments, pooled investment vehicles, or investment strategies are not necessarily indicative of future results. Excluded from this list are investments (and certain publicly traded cryptocurrencies/ digital assets) for which the issuer has not provided permission for JBV Capital to disclose publicly. As for its investments in any cryptocurrency or token project, JBV Capital is acting in its own financial interest, not necessarily in the interests of other token holders. JBV Capital has no special role in any of these projects or power over their management. JBV Capital does not undertake to continue to have any involvement in these projects other than as an investor and token holder, and other token holders should not expect that it will or rely on it to have any particular involvement.</p>
        <p>With respect to funds managed by JBV Capital that are registered in Japan, JBV Capital will provide to any member of the Japanese public a copy of such documents as are required to be made publicly available pursuant to Article 63 of the Financial Instruments and Exchange Act of Japan. Please contact JBV to request such documents.</p>
        <p>For other site terms of use, please go here. Additional important information about JBV Capital, including our Form ADV Part 2A Brochure, is available at the SEC’s website: <a href="http://www.adviserinfo.sec.gov" target="_blank" rel="noopener noreferrer">http://www.adviserinfo.sec.gov</a>.</p>
      </div>
    </main>
  );
}
// JBV: END privacy page

